# Generated by Django 4.1.1 on 2022-09-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PegarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('nome_moeda', models.CharField(choices=[('BRL', 'Real'), ('EUR', 'Euro'), ('JPY', 'Iene')], max_length=25)),
            ],
        ),
    ]
